from typing import Any

class PublicWebSocketClient:
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def ping(self) -> Any: ...
    async def time(self) -> Any: ...
    async def last_price(self, market: str) -> Any: ...
    async def market_depth(self, market: str) -> Any: ...
    async def market_stats(self, market: str) -> Any: ...
    async def market_stats_today(self, market: str) -> Any: ...
    async def market_trades(self, market: str) -> Any: ...
    async def kline(self, market: str, interval: str) -> Any: ...
    async def bookticker_subscribe(self, market: str) -> Any: ...
    async def bookticker_unsubscribe(self, market: str) -> Any: ...
    async def base_ws_requester(self, method: str, params: list[Any] | None = None) -> Any: ...
